<?php

declare(strict_types=1);

namespace App\Tests;

/*use Symfony\Component\Panther\PantherTestCase;*/

class TestCourseTest extends AbstractTest
{
    /*public function testSomething(): void
    {
        $client = static::createPantherClient();
        $crawler = $client->request('GET', '/');

        $this->assertSelectorTextContains('h1', 'Hello World');
    }*/
    protected function getFixtures(): array
    {
        return parent::getFixtures(); // TODO: Change the autogenerated stub
    }

    public function testSomething(): void
    {
        $client = AbstractTest::getClient();
        $url = '/course/';

        $crawler = $client->request('GET', $url);

        $link = $crawler->selectLink('Подробнее')->link();
        $crawler = $client->click($link);

        $this->assertResponseOk();
    }
}
