<?php

declare(strict_types=1);

namespace App\Tests\Controller;

/*use Symfony\Component\Panther\PantherTestCase;*/

use App\DataFixtures\AppFixtures;
use App\Entity\Course;
use App\Entity\Lesson;
use App\Tests\AbstractTest;
use Doctrine\Persistence\ObjectManager;

class TestCourseTest extends AbstractTest
{
    /*public function testSomething(): void
    {
        $client = static::createPantherClient();
        $crawler = $client->request('GET', '/');

        $this->assertSelectorTextContains('h1', 'Hello World');
    }*/
    protected function getFixtures(): array
    {
        return [AppFixtures::class];
        /*return parent::getFixtures(); */ // TODO: Change the autogenerated stub
    }

    public function testSomething(): void
    {

        $client = AbstractTest::getClient();
        $url = '/courses/';

        $crawler = $client->request('GET', $url);
        $this->assertResponseOk();

        $link = $crawler->selectLink('Создать')->link();
        $crawler = $client->click($link);
        $this->assertResponseOk();

        $link = $crawler->selectLink('Сохранить')->link();
        $crawler = $client->click($link);
        $this->assertResponseOk();
       /* $link = $crawler->selectLink('Создать')->link();
        $crawler = $client->click($link);*/

        /*$this->assertResponseOk();*/
        /*$this->assertResponseNotFound();*/
       /* $link = $crawler->selectLink('Добавить урок')->link();
        $crawler = $client->click($link);
        $this->assertResponseOk();*/
    }
}
